version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: facebookapiDB
    ports:
      - "27017:27017"
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: facebookapiExpress
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=luantang
      - ME_CONFIG_BASICAUTH_PASSWORD=2102
      - ME_CONFIG_MONGODB_ENABLE_ADMIN:true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - useBasicAuth=true
volumes:
  data: {}

networks:
  default:
    name: facebookapiNetwork